"""Write the packaged files a problem repo needs into that repo.

Three of them, each its own flag.  pset.tex is the macro contract and the
only one a repo cannot do without: hand-writing those definitions is how
a document ends up printing its answers on the student copy, so --init
generates them instead (see write_mechanism).

--example writes a whole working repo around it, problems and an
assignment included, since the layout is easier to copy than to describe.
README_pset.md is offered separately because a repo may not want one: the
CS1800 repo, say, documents itself already.  That answer is remembered
under the user's config folder, so the question is asked once rather than
on every scaffold.
"""

import pathlib
import re
import shutil
import sys
from importlib.resources import as_file, files
from typing import Optional

from ._version import __version__
from .config import MECHANISM, PROBLEMS, README, pref_file, pref_get, pref_set

EXAMPLE = 'pset_example'

# The remembered answer to "write README_pset.md?".  Named for the
# question, not the flag, since --readme asks for one unconditionally.
PREF_README = 'readme'

# Placeholder in the packaged pset.tex, and the line it becomes.  Reading
# the version back out is what lets --init tell an upgrade from a no-op,
# and what stops it overwriting a file it did not write.
VERSION_MARK = 'PSET_VERSION'

STAMP = re.compile(r'^% pset mechanism, generated by pset (\S+)\.',
                   re.MULTILINE)


def ask_readme(default: bool = True) -> bool:
    """Ask whether to write README_pset.md, once, and remember the answer.

    Args:
        default: what an empty reply means

    Returns:
        wanted: the remembered answer where one exists, otherwise what
            the user says now.  The default without asking when stdin is
            not a terminal, since a scripted run has nobody to answer and
            must not block on the prompt.
    """
    remembered = pref_get(PREF_README)
    if remembered is not None:
        return remembered
    if not sys.stdin.isatty():
        return default

    prompt = f'write {README} (how to use pset, for whoever clones this)?'
    suffix = '[Y/n]' if default else '[y/N]'
    try:
        reply = input(f'{prompt} {suffix} ').strip().lower()
    except EOFError:
        reply = ''
    wanted = default if not reply else reply.startswith('y')

    pref_set(PREF_README, wanted)
    print(f'    remembered, change it in {pref_file()}')
    return wanted


def write_readme(root: pathlib.Path, force: bool = False) -> Optional[
        pathlib.Path]:
    """Copy README_pset.md to a repo root, beside its problems folder.

    Args:
        root: the repo root to write into
        force: overwrite an existing copy.  Left False the existing one
            wins, since a repo may have edited it.

    Returns:
        path: the file written, None where one was already there
    """
    out = root / README
    if out.exists() and not force:
        return None
    shutil.copyfile(str(files('pset') / 'data' / README), out)
    return out


def read_stamp(path: pathlib.Path) -> Optional[str]:
    """Read the pset version a generated pset.tex was written by.

    Returns:
        version: None where the file is missing, unreadable, or carries no
            stamp.  The last case means someone wrote it by hand, and is
            the one --init refuses to overwrite.
    """
    try:
        found = STAMP.search(path.read_text(errors='ignore'))
    except OSError:
        return None
    return found.group(1) if found else None


def write_mechanism(root: pathlib.Path) -> tuple[pathlib.Path, str]:
    """Write pset.tex, the macro contract, to a repo root.

    Regenerated rather than merged: the file states pset's own contract,
    so an upgrade should carry the whole of it.  The one thing not
    overwritten is a pset.tex with no version stamp, which pset did not
    write and may be a repo's own preamble under the same name.

    Args:
        root: the repo root to write into

    Returns:
        path: the file
        state: what happened, one of 'wrote', 'upgraded from X',
            'already current' or 'kept' (the unstamped case)
    """
    out = root / MECHANISM
    before = read_stamp(out) if out.exists() else None
    if out.exists() and before is None:
        return out, 'kept'

    text = (files('pset') / 'data' / MECHANISM).read_text()
    out.write_text(text.replace(VERSION_MARK, __version__))

    if before is None:
        return out, 'wrote'
    if before == __version__:
        return out, 'already current'
    return out, f'upgraded from {before}'


def init(root: pathlib.Path, readme: Optional[bool] = None) -> pathlib.Path:
    """Set an existing repo up for pset, and print the line to add.

    Writes only pset.tex (and README_pset.md if asked): a repo that
    already has assignments has its own preamble and layout, and neither
    is pset's to rewrite.  The \\input line is printed rather than edited
    in, since where it belongs depends on a layout only the author knows.

    Args:
        root: the repo root
        readme: write README_pset.md, or None to leave it alone

    Returns:
        path: the pset.tex written
    """
    path, state = write_mechanism(root)
    print(f'{state}: {path}')

    if readme:
        written = write_readme(root)
        print(f'wrote {written}' if written
              else f'{root / README} exists already, left alone')

    if state != 'kept':
        print(f'\ninput it from each document, beside your other shared '
              f'preamble:\n\n    \\input{{../{MECHANISM}}}\n\n'
              f'or once from the preamble every document already inputs.  '
              f'The path is\nrelative to the document being built, not to '
              f'the file holding the line.')
    else:
        print(f'\n{path} carries no pset stamp, so it was left alone.  '
              f'Delete it and\nrerun to take the generated one.')
    return path


def scaffold(out: Optional[pathlib.Path] = None,
             readme: Optional[bool] = None) -> pathlib.Path:
    """Write the example problem repo.

    Args:
        out: the folder to create, defaulting to pset_example/ in the
            working folder
        readme: write README_pset.md, or None to use the remembered
            answer and ask if there is none

    Returns:
        root: the folder written

    Raises:
        FileExistsError: the folder is already there.  Refused rather
            than merged, so a repo that grew from an earlier scaffold is
            never half-overwritten.
    """
    root = pathlib.Path(out or EXAMPLE)
    if root.exists():
        raise FileExistsError(f'{root} exists already, name another folder')

    with as_file(files('pset') / 'data' / 'example') as source:
        shutil.copytree(source, root)

    # Through the same writer --init uses, rather than shipping a second
    # copy in the example folder that would drift from the first.
    write_mechanism(root)

    if readme is None:
        readme = ask_readme()
    if readme:
        write_readme(root)

    count = len(list((root / PROBLEMS).glob('**/*.tex')))
    print(f'wrote {root}/: {count} problems in '
          f'{len(list((root / PROBLEMS).iterdir()))} topics')
    print(f'    cd {root / "hw_example"} && pset hw_example')
    return root
