"""Tests for the parts where being wrong is expensive.

Two of the three are about \\input resolution, because that is where the
bugs have been: pdflatex reads every \\input relative to the folder it
runs in, and a walk that resolves against the including file instead
agrees just often enough to look correct.  Getting it wrong makes
uses_macro go blind, which silently un-skips every copy in a repo.

No pdflatex here.  The build itself is covered by building the example.
"""

import pathlib
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from pset.build import resolve, uses_macro
from pset.config import MECHANISM, find_repo
from pset.example import read_stamp, write_mechanism
from pset.usage import pair, problem_keys


def write(root, name, text=''):
    """Write one file, making its folders, and give back its path."""
    path = pathlib.Path(root) / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return path


@pytest.fixture
def repo(tmp_path):
    """Build a repo shaped like the real ones: documents one folder down.

    The preamble sits at the root and is what pulls in pset.tex, which is
    the arrangement that broke uses_macro: the \\input{../pset.tex} inside
    it has to resolve from hw1/, not from the root.
    """
    write(tmp_path, 'pset.tex', '% pset mechanism, generated by pset 0.0.0.\n'
                                r'\newcommand{\sol}[1]{}')
    write(tmp_path, 'command.tex', '\\input{../pset.tex}\n')
    write(tmp_path, 'problems/topic/with_rub.tex',
          'q\n\\sol{a}\n\\rub{2 pts}\n')
    write(tmp_path, 'problems/topic/sol_only.tex', 'q\n\\sol{a}\n')
    write(tmp_path, 'hw1/hw1.tex',
          '\\documentclass{article}\n\\input{../command.tex}\n'
          '\\begin{document}\n'
          '\\prob{[2 pts]: a}\n\\input{../problems/topic/sol_only.tex}\n'
          '\\end{document}\n')
    write(tmp_path, 'hw2/hw2.tex',
          '\\documentclass{article}\n\\input{../command.tex}\n'
          '\\begin{document}\n'
          '\\prob{[2 pts]: a}\n\\input{../problems/topic/with_rub.tex}\n'
          '\\end{document}\n')
    return tmp_path


class TestUsesMacro:
    """The \\input walk, which decides which copies get skipped."""

    def test_nested_input_from_the_root_is_not_blind(self, repo):
        # The regression: \input{../pset.tex} inside a root-level
        # command.tex resolved to outside the repo, so the walk went
        # blind and returned None, and every rub copy got built.
        assert uses_macro(repo / 'hw1/hw1.tex', 'rub') is False

    def test_finds_a_macro_through_two_levels(self, repo):
        assert uses_macro(repo / 'hw2/hw2.tex', 'rub') is True
        assert uses_macro(repo / 'hw1/hw1.tex', 'sol') is True

    def test_missing_input_reports_blind_not_absent(self, repo):
        write(repo, 'hw3/hw3.tex', '\\input{../gone.tex}\n')
        assert uses_macro(repo / 'hw3/hw3.tex', 'rub') is None

    def test_macro_built_path_reports_blind(self, repo):
        write(repo, 'hw4/hw4.tex', '\\input{\\covsrc/x.tex}\n')
        assert uses_macro(repo / 'hw4/hw4.tex', 'rub') is None

    def test_a_cycle_terminates(self, repo):
        write(repo, 'a.tex', '\\input{b.tex}')
        write(repo, 'b.tex', '\\input{a.tex}')
        assert uses_macro(repo / 'a.tex', 'rub') is False


class TestFindRepo:
    """Walking up to the repo root, from anywhere inside it."""

    def test_from_a_subfolder(self, repo):
        assert find_repo(repo / 'hw1') == repo

    def test_from_the_root(self, repo):
        assert find_repo(repo) == repo

    def test_outside_a_repo_raises(self, tmp_path):
        from pset.config import RepoError
        with pytest.raises(RepoError):
            find_repo(tmp_path)


class TestMechanism:
    """Generating pset.tex, and knowing when not to overwrite it."""

    def test_writes_and_stamps(self, tmp_path):
        path, state = write_mechanism(tmp_path)
        assert state == 'wrote'
        assert read_stamp(path) is not None

    def test_second_run_is_a_no_op(self, tmp_path):
        write_mechanism(tmp_path)
        _, state = write_mechanism(tmp_path)
        assert state == 'already current'

    def test_upgrades_an_older_stamp(self, tmp_path):
        path, _ = write_mechanism(tmp_path)
        path.write_text(path.read_text().replace(
            read_stamp(path), '0.0.1', 1))
        _, state = write_mechanism(tmp_path)
        assert state == 'upgraded from 0.0.1'

    def test_refuses_a_hand_written_file(self, tmp_path):
        mine = write(tmp_path, MECHANISM, '% mine\n\\newcommand{\\sol}[1]{#1}')
        _, state = write_mechanism(tmp_path)
        assert state == 'kept'
        assert mine.read_text() == '% mine\n\\newcommand{\\sol}[1]{#1}'

    def test_generated_file_hides_answers_by_default(self, tmp_path):
        # The whole reason this file is generated: with no \showsol, \sol
        # must expand to nothing.
        path, _ = write_mechanism(tmp_path)
        text = path.read_text()
        assert r'\newcommand{\sol}[1]{}' in text
        assert r'\newcommand{\rub}[1]{}' in text
        # and the flags must not be named after the macros
        assert r'\ifdefined\showsol' in text
        assert r'\ifdefined\sol' not in text


class TestUsage:
    """Pairing problems against the assignments that input them."""

    def test_pairs_both_ways(self, repo):
        keys = problem_keys(repo)
        files = [repo / 'hw1/hw1.tex', repo / 'hw2/hw2.tex']
        prob_to_file, file_to_prob = pair(files, keys, repo)
        assert prob_to_file['topic/sol_only'] == ['hw1/hw1']
        assert file_to_prob['hw2/hw2'] == ['topic/with_rub']

    def test_suffixed_and_bare_inputs_land_on_one_key(self, repo):
        # The bug in the old per-repo script: it matched by substring, so
        # an \input carrying the documented .tex suffix missed entirely.
        write(repo, 'hw5/hw5.tex', '\\input{../problems/topic/sol_only}\n')
        write(repo, 'hw6/hw6.tex', '\\input{../problems/topic/sol_only.tex}\n')
        keys = problem_keys(repo)
        prob_to_file, _ = pair(
            [repo / 'hw5/hw5.tex', repo / 'hw6/hw6.tex'], keys, repo)
        assert prob_to_file['topic/sol_only'] == ['hw5/hw5', 'hw6/hw6']

    def test_unused_problem_keeps_an_empty_list(self, repo):
        prob_to_file, _ = pair([repo / 'hw1/hw1.tex'], problem_keys(repo),
                               repo)
        assert prob_to_file['topic/with_rub'] == []


class TestResolve:
    """Turning command-line arguments into documents to build."""

    def test_suffix_is_optional(self, repo, monkeypatch):
        monkeypatch.chdir(repo / 'hw1')
        assert resolve(['hw1']) == [pathlib.Path('hw1.tex')]

    def test_a_sibling_build_collapses_onto_its_source(self, repo,
                                                       monkeypatch):
        monkeypatch.chdir(repo / 'hw1')
        (repo / 'hw1/hw1.pdf').write_text('')
        (repo / 'hw1/hw1_sol.pdf').write_text('')
        assert resolve(['hw1*']) == [pathlib.Path('hw1.tex')]

    def test_a_name_matching_nothing_raises(self, repo, monkeypatch):
        monkeypatch.chdir(repo)
        with pytest.raises(FileNotFoundError):
            resolve(['nope'])
